version: "3.9"

services:
  db:
    image: postgres:17
    container_name: ecommerce-db
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: ecommerce-web
    command: bash -c "./entrypoint.sh"
    ports:
      - "8000:8080"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
